# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Personal site
email: allrealelements@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome personal site which is going to be under construction for some time. This is merely a test.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://allrealelements.github.io" # the base hostname & protocol for your site
twitter_username: allrealelements
github_username:  allrealelements

# Build settings
markdown: kramdown
